/**
 * 한국에서 부르는 게임 이름 → 스팀 영어 검색어.
 * 스팀에 한글 이름이 없는 게임도 한글(줄임말 포함)로 찾을 수 있게 해준다.
 * 앱 ID 대신 검색어를 저장해서, 실제 게임 정보는 항상 스팀에서 가져온다.
 * 새 게임을 추가하려면 한 줄만 넣으면 된다.
 */
export interface KoreanAlias {
  ko: string[];
  en: string;
}

export const KOREAN_ALIASES: KoreanAlias[] = [
  { ko: ["델타 포스", "델포"], en: "Delta Force" },
  { ko: ["배틀그라운드", "배그", "펍지"], en: "PUBG: BATTLEGROUNDS" },
  { ko: ["카운터 스트라이크 2", "카스", "카스2"], en: "Counter-Strike 2" },
  { ko: ["도타 2", "도타"], en: "Dota 2" },
  { ko: ["엘든 링"], en: "ELDEN RING" },
  { ko: ["에이펙스 레전드", "에펙"], en: "Apex Legends" },
  { ko: ["로스트아크", "로아"], en: "Lost Ark" },
  { ko: ["메이플스토리", "메이플"], en: "MapleStory" },
  { ko: ["스타듀 밸리", "스듀"], en: "Stardew Valley" },
  { ko: ["몬스터 헌터 와일즈", "몬헌 와일즈", "몬헌"], en: "Monster Hunter Wilds" },
  { ko: ["몬스터 헌터 월드", "몬헌 월드"], en: "Monster Hunter: World" },
  { ko: ["몬스터 헌터 라이즈", "몬헌 라이즈"], en: "Monster Hunter Rise" },
  { ko: ["GTA 5", "그랜드 테프트 오토 5", "지티에이"], en: "Grand Theft Auto V" },
  { ko: ["레드 데드 리뎀션 2", "레데리"], en: "Red Dead Redemption 2" },
  { ko: ["사이버펑크 2077", "사펑"], en: "Cyberpunk 2077" },
  { ko: ["위쳐 3", "위처 3"], en: "The Witcher 3" },
  { ko: ["발더스 게이트 3", "발더스"], en: "Baldur's Gate 3" },
  { ko: ["팰월드"], en: "Palworld" },
  { ko: ["리썰 컴퍼니"], en: "Lethal Company" },
  { ko: ["어몽어스"], en: "Among Us" },
  { ko: ["테라리아"], en: "Terraria" },
  { ko: ["하데스 2"], en: "Hades II" },
  { ko: ["하데스"], en: "Hades" },
  { ko: ["할로우 나이트"], en: "Hollow Knight" },
  { ko: ["실크송", "할로우 나이트 실크송"], en: "Hollow Knight: Silksong" },
  { ko: ["다크 소울 3", "다크소울"], en: "DARK SOULS III" },
  { ko: ["세키로"], en: "Sekiro: Shadows Die Twice" },
  { ko: ["P의 거짓", "피의 거짓"], en: "Lies of P" },
  { ko: ["검은 신화 오공", "오공"], en: "Black Myth: Wukong" },
  { ko: ["스텔라 블레이드", "스블"], en: "Stellar Blade" },
  { ko: ["데이브 더 다이버", "데이브"], en: "DAVE THE DIVER" },
  { ko: ["클레르 옵스퀴르 익스페디션 33", "33원정대"], en: "Clair Obscur: Expedition 33" },
  { ko: ["배틀필드", "배필"], en: "Battlefield" },
  { ko: ["콜 오브 듀티", "콜옵"], en: "Call of Duty" },
  { ko: ["레인보우 식스 시즈", "레식"], en: "Rainbow Six Siege" },
  { ko: ["오버워치 2", "오버워치", "옵치"], en: "Overwatch 2" },
  { ko: ["데스티니 가디언즈 2", "데스티니"], en: "Destiny 2" },
  { ko: ["워프레임"], en: "Warframe" },
  { ko: ["패스 오브 엑자일 2", "패오엑"], en: "Path of Exile 2" },
  { ko: ["디아블로 4", "디아"], en: "Diablo IV" },
  { ko: ["러스트"], en: "Rust" },
  { ko: ["아크 서바이벌"], en: "ARK: Survival Ascended" },
  { ko: ["발하임"], en: "Valheim" },
  { ko: ["굶지마 투게더", "굶지마"], en: "Don't Starve Together" },
  { ko: ["프로젝트 좀보이드", "좀보이드"], en: "Project Zomboid" },
  { ko: ["파스모포비아", "파스모"], en: "Phasmophobia" },
  { ko: ["데드 바이 데이라이트", "데바데"], en: "Dead by Daylight" },
  { ko: ["레프트 4 데드 2", "레포데"], en: "Left 4 Dead 2" },
  { ko: ["팀 포트리스 2", "팀포"], en: "Team Fortress 2" },
  { ko: ["게리 모드", "게모"], en: "Garry's Mod" },
  { ko: ["포탈 2"], en: "Portal 2" },
  { ko: ["하프라이프"], en: "Half-Life" },
  { ko: ["문명 6"], en: "Sid Meier's Civilization VI" },
  { ko: ["문명 7", "문명"], en: "Sid Meier's Civilization VII" },
  { ko: ["스텔라리스"], en: "Stellaris" },
  { ko: ["하츠 오브 아이언 4", "하오아"], en: "Hearts of Iron IV" },
  { ko: ["크루세이더 킹즈 3", "크킹"], en: "Crusader Kings III" },
  { ko: ["토탈 워 워해머 3", "토탈워"], en: "Total War: WARHAMMER III" },
  { ko: ["시티즈 스카이라인"], en: "Cities: Skylines" },
  { ko: ["팩토리오"], en: "Factorio" },
  { ko: ["새티스팩토리"], en: "Satisfactory" },
  { ko: ["림월드"], en: "RimWorld" },
  { ko: ["슬레이 더 스파이어", "슬더스"], en: "Slay the Spire" },
  { ko: ["발라트로"], en: "Balatro" },
  { ko: ["뱀파이어 서바이버즈", "뱀서"], en: "Vampire Survivors" },
  { ko: ["리스크 오브 레인 2", "리오레"], en: "Risk of Rain 2" },
  { ko: ["딥 락 갤럭틱", "딥락"], en: "Deep Rock Galactic" },
  { ko: ["헬다이버즈 2", "헬다"], en: "HELLDIVERS 2" },
  { ko: ["씨 오브 시브즈"], en: "Sea of Thieves" },
  { ko: ["유로 트럭 시뮬레이터 2", "유로트럭", "유트시"], en: "Euro Truck Simulator 2" },
  { ko: ["포르자 호라이즌 5", "포르자"], en: "Forza Horizon 5" },
  { ko: ["철권 8", "철권"], en: "TEKKEN 8" },
  { ko: ["스트리트 파이터 6", "스파6"], en: "Street Fighter 6" },
  { ko: ["페르소나 5 로열", "페르소나"], en: "Persona 5 Royal" },
  { ko: ["파이널 판타지 14", "파판14", "파판"], en: "FINAL FANTASY XIV Online" },
  { ko: ["바이오하자드 RE:4", "레지던트 이블 4", "바하4"], en: "Resident Evil 4" },
  { ko: ["선즈 오브 더 포레스트"], en: "Sons Of The Forest" },
  { ko: ["더 포레스트"], en: "The Forest" },
  { ko: ["잇 테이크 투"], en: "It Takes Two" },
  { ko: ["스플릿 픽션"], en: "Split Fiction" },
  { ko: ["더 파이널스"], en: "THE FINALS" },
  { ko: ["마블 라이벌즈", "마라"], en: "Marvel Rivals" },
  { ko: ["나라카 블레이드포인트", "나라카"], en: "NARAKA: BLADEPOINT" },
  { ko: ["워썬더"], en: "War Thunder" },
  { ko: ["스케줄 원"], en: "Schedule I" },
  { ko: ["레포"], en: "R.E.P.O." },
  { ko: ["피크"], en: "PEAK" },
  { ko: ["인조이"], en: "inZOI" },
  { ko: ["원스 휴먼"], en: "Once Human" },
  { ko: ["인슈라우디드"], en: "Enshrouded" },
  { ko: ["서브노티카"], en: "Subnautica" },
  { ko: ["노 맨즈 스카이"], en: "No Man's Sky" },
  { ko: ["킹덤 컴 딜리버런스 2", "킹덤컴"], en: "Kingdom Come: Deliverance II" },
  { ko: ["호그와트 레거시"], en: "Hogwarts Legacy" },
  { ko: ["갓 오브 워"], en: "God of War" },
  { ko: ["다잉 라이트 2", "다잉 라이트"], en: "Dying Light 2" },
  { ko: ["폴아웃 4", "폴아웃"], en: "Fallout 4" },
  { ko: ["스카이림"], en: "The Elder Scrolls V: Skyrim Special Edition" },
  { ko: ["스파이더맨"], en: "Marvel's Spider-Man" },
];
